### ISSUE TITLE
Improve Slack and Twitter embeds/previews

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#165]
@stefanprodan says:

> can we restore all the head tags we had
> so that Slack and Twitter embeds look nice
> we lost the cuttlefish log, the description, etc

**Comment by hiddeco** [comment]
This is not just pretty but of high value for previews on social media, as it makes tweets much bigger and much more call-to-action.

**Comment by dholbach** [comment]
https://www.docsy.dev/docs/adding-content/shortcodes/#blockscover has a mention of Twitter cards.

**Comment by dholbach** [comment]
https://github.com/squidfunk/mkdocs-material/blob/master/material/overrides/main.html and https://github.com/squidfunk/mkdocs-material/blob/master/material/overrides/main.html is what (at least I believe) was driving the `mkdocs-material` theme's embeds. (It's what we used in our site before ... and still use over at <https://docs.fluxcd.io>.)

**Comment by dholbach** [comment]
Apparently we get pull these in Docsy:

```
{{- template "_internal/opengraph.html" . -}}
{{- template "_internal/google_news.html" . -}}
{{- template "_internal/schema.html" . -}}
{{- template "_internal/twitter_cards.html" . -}}
```
These templates can be found here: https://github.com/gohugoio/hugo/tree/master/tpl/tplimpl/embedded/templates


There's https://gohugo.io/templates/internal/#configure-twitter-cards to understand how to use Twitter cards as well.

Maybe we can set a default image somewhere?

**Comment by dholbach** [comment]
Unfortunately not quite closed yet...? Looks like https://cards-dev.twitter.com/validator still loads the old image even if all fluxcd.io pages now have:

```html
<meta name=twitter:image content="/img/flux-social.png">
```

and the file can be accessed just fine. It worked in the preview build. :man_shrugging:

**Comment by dholbach** [comment]
On Slack this seems to be working - maybe it's a caching thing over at Twitter?

**Comment by stefanprodan** [comment]
Twitter embeds are broken indeed 
<img width="578" alt="Screenshot 2021-06-02 at 19 14 56" src="https://user-images.githubusercontent.com/3797675/120515375-ece85980-c3d6-11eb-89d6-6633b19cd434.png">

**Comment by dholbach** [comment]
It'd be great if the previews also had some kind of markup, so that something like https://fluxcd.io/docs/cmd/flux_trace/ comes out great too.

**Comment by juozasg** [comment]
Can you verify that it is broken? I'm getting this:
![image](https://user-images.githubusercontent.com/4100/129246651-ee832bd4-90bb-4d2f-9632-d8b94665caad.png)

from the card validator for this: https://fluxcd.io/legacy/flux/get-started/

**Comment by juozasg** [comment]
I don't see that opensocial or twitter card metadata tags support any kind of markup. I tried it and found that Slack won't render anything if you try to put markup in the metadata tag. References suggest 2-4 sentences of text. 

Few ideas/research:

1. Use image metadata to show a page preview render - instead of flux logo. Maybe a service/CI can provide this? Maybe oEmbed is helpeful. Info: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254
2. Find/build a Slack plugin service to render unfurls: https://medium.com/slack-developer-blog/all-will-be-revealed-ebcad7c531f0
3. Improve cmd docs metadata generation.

The last option seems least complicated.

I don't fully understand the doc content generation, but for flux commands it looks that docgen needs to extract some description from the markdown `cobra` generates. Either cut something from the markdown body or use cobra.Command.Short contents for description metadata. The smallest change would be to just set static description like "Flux command documentation", like it currently is with CRDs description metadata, where each CRD says "The GitOps Toolkit Custom Resource Definitions documentation." It's not much information, but it looks better than this:

![Screenshot from 2021-08-12 23-47-26](https://user-images.githubusercontent.com/4100/129267528-530ab8d5-ac50-4c4c-a4c0-4673177203b1.png)
