### ISSUE TITLE
"Other Flux projects" section items not centered

### ISSUE THREAD

**Issue by juozasg** [fluxcd/website#324]
"GitOps Toolkit" and "Flagger" boxes are not centered. Especially noticeable on mobile.

**Comment by hiddeco** [comment]
Noticed this too, another thing is that on ultra-wide screens (38" in my case), the page now goes outside the container making everything harder to read because I now have to move my head (or try to see sharp in the corners of my sight).

![image](https://user-images.githubusercontent.com/10063039/121950480-f6b87800-cd59-11eb-99ec-4f61bb90d689.png)

**Comment by hiddeco** [comment]
A question related to the hero that has also changed: is the shadow on the H1 on purpose? If I disable it, it looks nicer (and less web 2.0?) to me.

**Comment by juozasg** [comment]
Another, somewhat related issue is there is a narrow white vertical margin across the entire right side of the front page. It is not normally visible but scrolling the page to the right shows it. And it causes a horizontal scroll bar to appear on the bottom of the page. These alignment issues should be fixed in a same PR. 

![image](https://user-images.githubusercontent.com/4100/123028747-26403380-d39d-11eb-802d-998ec127fe8e.png)

**Comment by juozasg** [comment]
@hiddeco I have copied your feedback on H1 drop shadow to #136.
